#!/usr/bin/env bash
# Displays information about subdomains

domain=$1
subdomain=$2

test_subdomain() {
    result=$(dig "$1.$domain" | grep -A1 "ANSWER SECTION:" | tail -n1)

    record_type=$(echo "$result" | awk '{print $4}')
    destination=$(echo "$result" | awk '{print $5}')

    echo "The subdomain $1 is a $record_type record and points to $destination"
}

if [ -z "$subdomain" ]; then
    test_subdomain "www"
    test_subdomain "lb-01"
    test_subdomain "web-01"
    test_subdomain "web-02"
else
    test_subdomain "$subdomain"
fi